### ISSUE TITLE
Unable to run Sorbet on CircleCI

### ISSUE THREAD

**Issue by coding-bunny** [sorbet/sorbet#5754]
#### Input
Setup a step in our CircleCI configuration like so:

```yaml
  sorbet:
    description: "Runs the Sorbet static code checker for type compatibility"
    steps:
      - run:
          name: "Sorbet"
          command: bundle exec srb tc
```

And invoke is part of the workflow.

#### Observed output

The command fails about not being able to find something related to Sorbet.
```
#!/bin/sh -eo pipefail
bundle exec srb tc

/root/project/vendor/bundle/ruby/3.1.0/gems/sorbet-0.5.9976/bin/srb: line 109: /root/project/vendor/bundle/ruby/3.1.0/gems/sorbet-static-0.5.9976-x86_64-linux/libexec/sorbet: No such file or directory

Exited with code exit status 127

CircleCI received exit code 127
```

#### Expected behavior
I expect the command to just work and run

- - -

Everything works just fine on local development systems.
Did install `bash` as additional dependency on the CircleCI runtime.
We're using the `ruby:3.1.0-alpine` Docker Image for running everything.
