### ISSUE TITLE
Add a config to make sorbet show a full stack trace

### ISSUE THREAD

**Issue by jagthedrummer** [sorbet/sorbet#8167]
### Problem

I don't use sorbet in _my_ project, but some of the gems that I use do. I'm trying to upgrade a particular gem to a new version. After upgrading _that_ gem I run my tests and sorbet throws a `TypeError` that points to a _different_ gem (not the one I'm upgrading). The error only contains a single line that points to the place that the type violation is occurring, but I have no idea what the call stack looks like that makes it arrive at that point.

```
Failures:

  1) DashboardController GET #index returns http success
     Failure/Error: get :index

     TypeError:
       T.let: Expected type Integer, got type String with value "1726173328"
       Caller: /Users/jgreen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/shopify_api-14.4.0/lib/shopify_api/auth/jwt_payload.rb:34
     # ./spec/controllers/dashboard_controller_spec.rb:12:in `block (3 levels) in <top (required)>'
```

### Proposed solution

It would be nice to be able to set a config setting, or environment variable to make sorbet display the entire trace that leads up to a type violation.
